import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Update the import
import "./globals.css";
import Navbar from '@/components/Navbar';

const montserrat = Montserrat({ subsets: ["latin"] }); // Use Montserrat

export const metadata: Metadata = {
  title: "Portfolio - 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={montserrat.className}> {/* Apply Montserrat font */}
        <div className="relative w-full flex items-center justify-center">
          {/* <Navbar /> */}
        </div>
        {children}
      </body>
    </html>
  );
}
