import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from "@/components/Footer";
import Head from 'next/head';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio - 2024",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="dark">
      <Head>
        <link rel="icon" href="/favicon.ico" />
        {/* Add other head elements here */}
      </Head>
      <body className={`${montserrat.className} flex flex-col min-h-screen`}>
        <div className="flex-grow">
          {/* Optionally include Navbar here if needed */}
          {children}
        </div>
        <footer className="w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
